### ISSUE TITLE
chromeOptions is not the name of a known capability or extension capability

### ISSUE THREAD

**Issue by rochacbruno** [jonhoo/fantoccini#36]
I download and installed `geckodriver`

```bash
wget https://github.com/mozilla/geckodriver/releases/{latest}linux64.tar.gz
tar -xvzf geckodriver*
chmod +x geckodriver
geckodriver
(running on port 4444)
```

Used this code:
```rust
extern crate tokio;
extern crate futures;
extern crate fantoccini;

fn main() {
    use fantoccini::{Client, Locator};
    use futures::future::Future;
    let c = Client::new("http://localhost:4444");
   
    // let's set up the sequence of steps we want the browser to take
    tokio::run(
        c
            .map_err(|e| {
                unimplemented!("failed to connect to WebDriver: {:?}", e)
            })
            .and_then(|c| {
                // first, go to the Wikipedia page for Foobar
                c.goto("https://en.wikipedia.org/wiki/Foobar")
            })
            .and_then(|mut c| c.current_url().map(move |url| (c, url)))
            .and_then(|(mut c, url)| {
                assert_eq!(url.as_ref(), "https://en.wikipedia.org/wiki/Foobar");
                // click "Foo (disambiguation)"
                c.find(Locator::Css(".mw-disambig"))
            })
            .and_then(|e| e.click())
            .and_then(|mut c| {
                // click "Foo Lake"
                c.find(Locator::LinkText("Foo Lake"))
            })
            .and_then(|e| e.click())
            .and_then(|mut c| c.current_url())
            .and_then(|url| {
                assert_eq!(url.as_ref(), "https://en.wikipedia.org/wiki/Foo_Lake");
                Ok(())
            })
            .map_err(|e| {
                panic!("a WebDriver command failed: {:?}", e);
            })
    );
}
```

Result:

```bash
$ cargo run   
   Compiling web_ui_testing v0.1.0 (file:///home/rochacbruno/Projects/rust/i_am_learning_rust/web_ui_testing)           
    Finished dev [unoptimized + debuginfo] target(s) in 2.62s
     Running `target/debug/web_ui_testing`
thread 'tokio-runtime-worker-2' panicked at 'unexpected webdriver error; webdriver returned error: chromeOptions is not the name of a known capability or extension capability', /home/rochacbruno/.cargo/registry/src/github.com-1ecc6299db9ec823/fantoccini-0.11.2/src/session.rs:314:17
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread 'tokio-runtime-worker-2' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:345:21
```

**Comment by rochacbruno** [comment]
Same problem on NIghlty

**Comment by rochacbruno** [comment]
There is a different error when using `WebKitWebDriver -p 4444`


```bash
 $ cargo run       
    Finished dev [unoptimized + debuginfo] target(s) in 0.10s                                                           
     Running `target/debug/web_ui_testing`
thread 'tokio-runtime-worker-2' panicked at 'unexpected webdriver error; webdriver returned error: Invalid alwaysMatch capabilities', /home/rochacbruno/.cargo/git/checkouts/fantoccini-37a5b9f98b789092/c1c515d/src/session.rs:314:17
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread 'tokio-runtime-worker-1' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:355:21

```

**Comment by jonhoo** [comment]
Ah, good catch! This is because WebDriver apparently now serializes legacy new session parameters incorrect (see https://github.com/jonhoo/fantoccini/commit/b030fc35467e61aee8aa5a3cd1767f6b80ba5b13). I'd worked around that by setting this capability, but it's Google Chrome specific, and I'd left off the vendor prefix (fixed in https://github.com/jonhoo/fantoccini/commit/65081ebccf5b394e41878fc0e75bce82736a79a4). I think this should now be fixed in the about-to-be-published 0.11.3!

**Comment by rochacbruno** [comment]
Thanks!

I used

```toml
[dependencies.fantoccini]
git = "https://github.com/jonhoo/fantoccini"
rev = "52cf5b1f763a5f19d3735bafd378fede9d193a07"
```

And now it works with `geckodriver`

ut using `WebKitWebDriver -p 4444` it still fails with

```bash
thread 'thread 'tokio-runtime-worker-2tokio-runtime-worker-3' panicked at '' panicked at 'not yet implemented: failed to connect to WebDriver: SessionNotCreated(WebDriverError { error: SessionNotCreated, message: "Failed to match capabilities", stack: "", delete_session: false })called `Option::unwrap()` on a `None` value', ', src/main.rslibcore/option.rs::14355::1721
```

@jonhoo I'll give a talk on saturday about testing strategies and Iam going to show Factoccini demo!

Thanks

**Comment by jonhoo** [comment]
That's truly bizarre. As far as I can tell, we're hitting [this line](https://github.com/WebKit/webkit/blob/fac272d49ea93ec55adb81cebc4bb3afa3f50f2e/Source/WebDriver/WebDriverService.cpp#L628) in WebKitWebDriver, but I don't see why the matched capabilities list would be empty. Can you try `chromedriver` instead?

**Comment by jonhoo** [comment]
Filed it as https://github.com/jonhoo/fantoccini/issues/37 :)
